name: "Bump & Tag"

on:
  push:
    branches:
      - "main"
      - "release"

jobs:
  bump-version:
    name: "Bump Version or Tag"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.FAST_FORWARD_PAT }}
        with:
          skip-tag: ${{ github.ref == 'refs/heads/main' }}
          skip-commit: ${{ github.ref == 'refs/heads/release' }}
