name: Bump & Tag

on:
  push:
    branches:
      - "main"
      - "release"

jobs:
  bump-version:
    name: "Bump Version or Tag"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      newTag: ${{ steps.bump.outputs.newTag }}

    if: ${{ github.actor != 'github-actions[bot]' }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ref: ${{ github.ref }}

      - name: "Debug - Output Actor" # Added debug step
        id: debug
        run: |
          echo "actor=${{ github.actor }}"
          echo "actor=${{ github.event.pusher.name }}"

      - name: "Automated Version Bump"
        id: bump
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_EMAIL: github-actions[bot]@users.noreply.github.com
        with:
          version-type: ${{ github.ref == 'refs/heads/release' && 'minor' || 'patch' }}
          commit-message: "chore: bumps version to {{version}}"
          bump-policy: "ignore"
          skip-push: "true"

      - name: "Create Tags and package version"
        run: |
          git push --follow-tags
          git push --tags

  create-release:
    name: "Create Release"
    needs: bump-version
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run NPM build
        uses: anna-money/github-actions-npm@master
        with:
          target: "build"
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**"
          generateReleaseNotes: true
          tag: ${{ needs.bump-version.outputs.newTag }}

  update-main:
    name: "Update main branch with release changes"
    needs: bump-version
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge release into main
        run: |
          git fetch origin release
          git merge origin/release
          git push origin main
