name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**"
          generateReleaseNotes: true
