name: HA Validations

on:
  push:
    branches:
      - 'main'
      - 'actions' # todo remove
  pull_request:
    branches:
      - 'main'

jobs:
  hassfest:
    name: 'Hassfest Validation'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Run hassfest validation'
        uses: 'home-assistant/actions/hassfest@master'

  hacs:
    name: 'HACS Validation'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Run HACS validation'
        uses: 'hacs/action@main'
        with:
          category: 'dashboard'
